### ISSUE TITLE
Ubuntu dependencies

### ISSUE THREAD

**Issue by sepastian** [jakobwilm/slstudio#11]
Hi, I'm just compiling your project and had to install two additional packages, so the dependencies for Ubuntu (16.04) become:

```
sudo apt-get install qt5-qmake libvtk6-qt-dev libpcl-dev libopencv-dev libglew-dev qtcreator qt5-default libusb-1.0-0-dev
```

`qt5-default` is required on systems that have both Qt4 and Qt5 installed. Without this package, qmake would fail on my machine.

`libusb-1.0-0-dev` is a dependency in `src/SLStudio.pro`.

**Comment by jakobwilm** [comment]
Thanks a lot Sepastian. I changed the readme accordingly.
