### ISSUE TITLE
Hardware Trigger 

### ISSUE THREAD

**Issue by nikkadim** [jakobwilm/slstudio#12]
I've a sync cable between camera and **LightCrafter 4500** and I switched **SLStudio** to _Hardware Triggering_, but from projector output (_TRIG_OUT1_) I see no pulse at the scope to trigger the camera. In a project README file you also mention that for realtime setup we have to use  _/tools/lc4500startup_ to prepare projector, but I did not find _LCR_SetTrigOutConfig_ function which makes output setup. Am I missed something? Thank you.
![ht](https://cloud.githubusercontent.com/assets/152394/20352819/b8c4e1d0-abe6-11e6-8ca6-25d65de0a56c.png)

PS: Another question - why grey-white checkerboard matters? Why not black-white?

**Comment by jakobwilm** [comment]
Hello. You can configure the projector using the TI GUI if lc4500startup does not work. Put it in pattern sequence mode with HDMI input. Set your graphics card to the native (diamond pixel) 914x1140 resolution. Please read our paper on calibration for an explanation.

**Comment by nikkadim** [comment]
Thanks @jakobwilm for the tip with _native_ resolution! 

That is really strange,  I set projector in pattern sequence mode and external (HDMI) pattern input as you  did in lc4500startup, but projector still showing anything and not sending output pulses to camera.

Here is the new SLStudio settings:
![log2](https://cloud.githubusercontent.com/assets/152394/20362633/512dfd3a-ac0a-11e6-8f7b-4f4f52ef7495.png)

console:
![log3](https://cloud.githubusercontent.com/assets/152394/20362020/e0e2b900-ac07-11e6-963b-6f76c913c73e.png)

and the projector settings:
![logg](https://cloud.githubusercontent.com/assets/152394/20362614/427c1196-ac0a-11e6-84a7-7bef8756122b.jpg)

Thank you in advance.

**Comment by jakobwilm** [comment]
Set pattern source to video port and trigger mode to vsync.

**Comment by nikkadim** [comment]
It's actually set. TI GUI .3.0.1 for some reason does not show this right.
I've added in lc4500startup.cpp reading procedures (LCR_Get...) just to check the current status after I set LCR_SetPatternDisplayMode and LCR_SetPatternTriggerMode:

>  nikk@STEREO-SYSTEM:~/slstudio/slstudio-master/tools/lc4500startup$ ./lc4500startup
> lc4500startup: preparing LightCrafter 4500 for duty... 
> LCR_GetPatternDisplayMode = 0
> LCR_GetPatternTriggerMode = 0
> done!


so everything looks right..

![s1](https://cloud.githubusercontent.com/assets/152394/20364197/36df7c3c-ac10-11e6-9dc4-ee718559cc51.jpg)
![s2](https://cloud.githubusercontent.com/assets/152394/20364198/36f0f6c4-ac10-11e6-8671-660029a74d5a.jpg)

**Comment by jakobwilm** [comment]
Well, the firmware and GUI have their quirks and bugs and usually take a few days to work around... The S172 looks a bit strange. Also, Pattern Sequence [Variable Exposure] is the new default mode. Maybe something was fixed in LC4500 api in the firmware 3 release. I would try setting it up using the GUI first in Variable Exposure.
