### ISSUE TITLE
"Perform Calibration" quits, & no dropdown access to webcam in preferences menu

### ISSUE THREAD

**Issue by morrisvanegas** [jakobwilm/slstudio#18]
Built on gt5 using SLStudio.pro configuration.
I can run SLStudio from inside my newly created build folder, but when I click "perform calibration" SLStudio quits with a "The program has unexpectedly finished." Is this because I have no calibration.xml file?

I can use cheese to preview my webcam (so I know I can see it), but the dropdown menu in Preference inside SLStudio only show "SLStudio Virtual Camera" as an option. Doesnt recognize my USB camera.

Despite two issues above, I tried running without calibration and with "SLStudio Virtual Camera" (Preferences: single point cloud acquisition, 2x3 pattern phase shift, Screen 0 projector, software trigger) and my point clouds are empty, presumably because I am not using my usb webcam.

What matlab shows when I open .pcd output file:
```
# .PCD v.7 - Point Cloud Data file format
VERSION .7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F I
COUNT 1 1 1 1
WIDTH 640
HEIGHT 512
POINTS 327680
DATA ascii
0.000000 0.000000 0.000000 255
0.000000 0.000000 0.000000 255
0.000000 0.000000 0.000000 255
0.000000 0.000000 0.000000 255
0.000000 0.000000 0.000000 255
0.000000 0.000000 0.000000 255
0.000000 0.000000 0.000000 255
0.000000 0.000000 0.000000 255
0.000000 0.000000 0.000000 255
0.000000 0.000000 0.000000 255
```
Any tips on calibration and webcam usage would be greatly appreciated!
(Also pardon simplicity in questions; first endeavor into c++)

Morris

xubuntu running 16.04.
Playstation eye camera
Sony MP-CL1A projector

**Comment by jakobwilm** [comment]
Hi Morris. 
Your camera is not supported. You would have to extend the camera wrappers for your camera. Presumably you could use OpenCV's camera capture interface.
Regards.
