### ISSUE TITLE
Multi scan merge

### ISSUE THREAD

**Issue by percramer** [jakobwilm/slstudio#19]
Hi,

i was wondering if there is anything in there that will merge scans if we need to do multiple scans to complete a full 360 scan?

Regards,

Per

**Comment by jakobwilm** [comment]
Hi Per,

there is a fast ICP implementation which is used for pose tracking. You could use it to start a merging process, but you would probably need to follow that with a global/groupwise registration of all part scans.

Regards, Jakob
