### ISSUE TITLE
Fail to run matlab determineGammaResponse script - Exception error? 

### ISSUE THREAD

**Issue by meardon** [jakobwilm/slstudio#26]
Hi Jakob,

I apologise for raising two issues in one day, but having looked at the code in the matlab directory, we do not understand what is going wrong seeing how early it bails out. 

We have built the matlab mex files successfully after the fix, but now when running determineGammaResponse we get an error on line 5 where it creates an projector object. Here is the output on the error below. Also we have been able to use the camera and projector with the SLStudio calibration. 

DLP Lightcrafter
XIMEA XiQ MG013MG-E2
Ubuntu 16.04 64-bit
matlab R2018a

```
Warning: The following error was caught while executing 'Projector' class destructor:
Error using ProjectorMex
Input must be a real uint64 scalar.

Error in Projector/delete (line 24)
            ProjectorMex('delete', this.objectHandle);

Error in Projector (line 18)
        function this = Projector(screenNum)

Error in determineGammaResponse (line 5)
p = Projector(1); 
> In Projector (line 18)
  In determineGammaResponse (line 5) 
Unexpected unknown exception from MEX file..

Error in Projector (line 19)
            this.objectHandle = ProjectorMex('new', screenNum);

Error in determineGammaResponse (line 5)
p = Projector(1);
```

**Comment by jakobwilm** [comment]
Hi meardon,
have you solved this?
/Jakob
