### ISSUE TITLE
the theory of the reconstruction?

### ISSUE THREAD

**Issue by Yuxishan2** [jakobwilm/slstudio#28]
strip or sepckle? 
is there any papers or tutorial about the encoding of the speckle translation?

**Comment by hcw70** [comment]
@jakobwilm Why was this issue closed without a comment? I would like to know also about the speckle translation.....

**Comment by jakobwilm** [comment]
The issue was closed because:
* The question is very vague and unclear.
* I have no idea what speckle translation is.
* This is obviously not an ISSUE with the software.
* The author should probably do some googling first.
