### ISSUE TITLE
X Error of failed request:  GLXBadDrawable

### ISSUE THREAD

**Issue by yangjingsen** [jakobwilm/slstudio#37]
When I compile with " SOURCES += projector/OpenGLContext.GLFW.cpp", the screen 1 shows, but whenever I scan or calibrae camera and projector, the following errors shows like :
X Error of failed request:  GLXBadDrawable
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  16 (X_GLXVendorPrivate)
  Serial number of failed request:  184
  Current serial number in output stream:  186
Any advice could help me? I've been looking for so long. 
Thanks!

**Comment by jakobwilm** [comment]
Sorry. This is very machine / OS / driver specific.
