### ISSUE TITLE
subpixel interpolation - greycode

### ISSUE THREAD

**Issue by DotZ1** [jakobwilm/slstudio#38]
Hi,

There is a comment in the GrayCode decoder codec as follows

// Binarize frames. TODO: subpixel interpolation.

How would you go about implementing sub pixel interpolation for the gray code patterns when acquired through the camera? Not looking for code but more the approach on how to tackle this?

Could the same technique work for the three phase images in 2x3 codec?

Thanks

Dot

**Comment by jakobwilm** [comment]
For Gray Coding, you would use the raw image's greyscale values to place the binary edge between integer coordinates. I have implemented this once and plan to integrate that method into SLStudio at some time.
