### ISSUE TITLE
No user forum - Pls Respond if you have worked with MicroPhaseShift etc

### ISSUE THREAD

**Issue by profHoneydew** [jakobwilm/slstudio#39]
Hi, 

I feel a bit silly trying to contact the community via an Git Issue - so maybe my issue is that there is not user forum for this project ;-)

Anyway, if anyone who sees this has SLStudio working and tried MicroPhaseShift, or indeed anything other than 2x3 and Grey code, could you please let me know how well it worked. 

The reason I ask is that the readme file recommends 2x3 explicitly - even through more advanced algorithms such as Micro Phase Shifting are present. Why recommend 2x3 with all the inherent phase unwrapping issues over better choices?   Are the implementations of Micro Phase Shifting etc somehow inferior?

**Comment by jakobwilm** [comment]
Hi. Please see the newly added examples which do reconstruct properly. Which codec to use is a long complex discussion. In essence, if there was a clear winner, we would not have to implement all methods. They all have their strengths/weaknesses relating to precision, dynamic range, robustness to lighting effects, etc.
