### ISSUE TITLE
State of Triangulator::triangulateFromUpVp

### ISSUE THREAD

**Issue by jan0e** [jakobwilm/slstudio#4]
Hi,

I've been tinkering around with SLstudio and I noticed the warning that the method used for triangulation when horizontal and vertical are activated is incomplete. Could you indicate the state of the method, e.g. is it somewhat working, what exactly is missing and may be provide a link to something describing the algorithm you wanted to implement?

Thanks for sharing your awesome work!
Cheers,
jan0e

**Comment by jakobwilm** [comment]
Hi jan0e,
it should be working actually. It is essentially just a call to OpenCVs triangulatePoints, which triangulates based four constraints. Please note that there is usually not much gained in doing this due to the epipolar geometry.
Regards, Jakob
