### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by zombicore** [jakobwilm/slstudio#42]
1- can i use another DLP3010EVM-LC ?  its about 103 Hz fresh rate for Real Time Structure
2- is there an option to use 2 cameras ? without code modification in triangulation 
( i will use Ximea MQ013RG-E2 )
3- does gpu processing works on windows ?

**Comment by jakobwilm** [comment]
Hello zombicore,

None of these features are supported at the moment. Thanks for making me aware of these use cases.

Sincerely
