### ISSUE TITLE
Different Outputs

### ISSUE THREAD

**Issue by goksubaser** [jakobwilm/slstudio#48]
Good Day Sir,

I was trying to work on your repository recently for my University Project. When I run the application, and scan the example data, the saved .pcd and .ply outputs result different than the "pointCloud.ply" outputs presented in the example_data/... folders. I wonder if there is an extra process needed to come up with presented "pointCloud.ply" after the scan is done. 

Ps: I get meaningful .pcd and .ply outputs from skull_3ps and skull_gray; however, the outputs are not the same as "example_data/skull_3ps/pointCloud.ply" and "example_data/skull_gray/pointCloud.ply" respectively. Resulting output files has more noise than the example ones. Resulting outputs are below.

skull_3ps Result:
![skull_3ps Result](https://user-images.githubusercontent.com/44346432/167792460-c7280edb-07a7-413a-9834-6964749934f8.png)
example_data/skull_3ps/pointCloud.ply:
![skull_3ps example_data](https://user-images.githubusercontent.com/44346432/167793651-95f64e8c-9a9b-4e57-99cd-91e38ca5da27.png)
-------------------------------------------------------------------------------------------------------------------------------------------------
skull_gray Result:
![skull_gray Result](https://user-images.githubusercontent.com/44346432/167792364-6c895a89-bf70-4fb2-97dd-1f0c47c103cc.png)
example_data/skull_gray/pointCloud.ply:
![skull_gray example_data](https://user-images.githubusercontent.com/44346432/167793831-d2b0da12-32fa-44c4-a563-73b721aa6833.png)
-------------------------------------------------------------------------------------------------------------------------------------------------

Sincerely.

**Comment by jakobwilm** [comment]
I believe you missed some settings. For PS: Have a look at the filtering steps. For Gray-coding: have a look at settings and constants in decoder. Please move to discussions.
