### ISSUE TITLE
Frequncy enquirment

### ISSUE THREAD

**Issue by CHNJQB** [jakobwilm/slstudio#57]
Hi ！
When I ran the software with my own data, I was unable to complete the final reconstruction.I suspect the frequency is wrong.
Does the software have requirements for the frequency of projected fringe?Is it necessary to project fringe patterns at specific frequencies?
Thank you very much.
![result](https://user-images.githubusercontent.com/122538150/217013815-9b78770c-19f0-4230-92c5-c8fc0151eb22.png)
![pointCloud](https://user-images.githubusercontent.com/122538150/217013919-c83ef305-bfd2-49f8-8b80-6fb13d11ac1e.png)

**Comment by jakobwilm** [comment]
Hello. Yes - of course.

**Comment by CHNJQB** [comment]
> Hello. Yes - of course.

Could you please tell me the frequency requirement?
Thank you very much！

**Comment by jakobwilm** [comment]
It needs to match decoder frequency. Studdy source code and theory.
This is not a software issue. Please stop using issue reports.

**Comment by CHNJQB** [comment]
OK！Thank you for your sincere answer.
