### ISSUE TITLE
Guide on how to compile?

### ISSUE THREAD

**Issue by gamerpaddy** [jakobwilm/slstudio#58]
Without being a lvl 9000+ Nerd on linux, how do you even compile and run it?
or on windows?

**Comment by AaronLK** [comment]
It does seem to compile pretty easily on Ubuntu 22:

```
sudo apt-get install libpcl-dev libopencv-dev libvtk9-qt-dev libglew-dev freeglut3-dev qtcreator libusb-1.0-0-dev qmake6 libxrandr-dev
git clone git@github.com:jakobwilm/slstudio.git
cd slstudio
mkdir qmake_build
cd qmake_build
qmake -makefile -o Makefile ../src/SLStudio.pro
make
./SLStudio
```

**Comment by CWB1999** [comment]
I also want to ask how to compile and run the project in the Windows system. I opened the project with QT creator 4.11 and met an error like the following:
Error while building/deploying project SLStudio (kit: Desktop Qt 5.14.2 MSVC2017 64bit)
The kit Desktop Qt 5.14.2 MSVC2017 64bit has configuration issues which might be the root cause for this problem.

**Comment by jakobwilm** [comment]
Hello. Unfortunately, building on Windows requires good knowledge of the toolchain and compilers. We might add automated builds in the future.

**Comment by 757dyar** [comment]
Dear Mr. Wilm,
Thank you very much for your work. Im working on an project which would really benifit from your codes.

I am using WSL2 (latest version) with ubuntu 22.04.  Mircosoft says that it can open open different linux apps such as chrome-linux, VLC-linux.

I followed the cmake procedures stated by Aaron in above comments.  My application was successfully made, but when open it it turns into a dark screen.

Do you have any idea on why that happens?  Thank you very much again!

Andy
<img width="718" alt="Capture" src="https://github.com/jakobwilm/slstudio/assets/135091308/226a7c01-0a37-4aa0-a4af-19041daf8142">
