### ISSUE TITLE
Gamma correction for second monitor setup?

### ISSUE THREAD

**Issue by pedroarroyo** [jakobwilm/slstudio#61]
Hi,

Currently I seem to be having issues stemming from the nonlinearity of my projector output.  I noticed that for the second monitor setup, there seems to be some gamma adjustment code that is commented out and not currently in use.  Is this still the right approach or was there a reason this is not implemented? 

  // Adjust gamma to one
  // setGamma(1.0);
}

void OpenGLContext::setGamma(float gamma) {
  // Adjust gamma
  //    XF86VidModeGamma xf86Gamma = {gamma, gamma, gamma};
  //    XF86VidModeSetGamma(contextInfo->display, screenNum, &xf86Gamma);
}

**Comment by jakobwilm** [comment]
Hi Pedro

I guess it is the right approach. Probably commented out due to compatibility issues.
