### ISSUE TITLE
Grey code encode/decode out of sync with sampling framerate?

### ISSUE THREAD

**Issue by pedroarroyo** [jakobwilm/slstudio#62]
Hi,

I am attempting to calibrate the system with grey code encoding set, and adjusting the shutter and delay to slow down the scanning process to try to ensure every frame is properly exposed.

I am using an LC4500 in pattern display mode as according to the manufacturer this allows the patterns to be projected with linear gamma response.

I am finding that some of the projected frames are black when I capture them, as well as some of the decoded frames still show the encoding pattern, which I believe might be the cause of my projector calibration showing a large reprojection error.  From reading other posts it appears that there is also a frequency dependency for the encoding of the patterns being projected?  I could not find any place where this is hardcoded but admittedly I am still new to the codebase.

Is there another place where we need to adjust the codec based on frequency?

**Comment by jakobwilm** [comment]
Hi.
Your calibration has nothing to do with the synchronization.
You need hardware triggering. See Readme and Arduino based example.
Sincerely
