### ISSUE TITLE
Compilation error in windows

### ISSUE THREAD

**Issue by Cynthia7** [jakobwilm/slstudio#9]
I am using Windows 7 with Qt 5.6.0. When I build this project, there is no bug, but 442 warnings and the compilation failed. The Compile Output includes many this kind of errors:
[ cl : Command line warning D9024 : unrecognized source file type 'Project/slstudio-master/build-SLStudio-Desktop_Qt_5_4_2_MSVC2012_OpenGL_32bit-Debug"', object file assumed
 cl : Command line warning D9027 : source file 'Project/slstudio-master/build-SLStudio-Desktop_Qt_5_4_2_MSVC2012_OpenGL_32bit-Debug"' ignored]

The final error that exit the process:
[jom: C:\Users\zhang.2669\Documents\Qt Project\slstudio-master\build-SLStudio-Desktop_Qt_5_4_2_MSVC2012_OpenGL_32bit-Debug\Makefile.Debug [debug\moc_SLStudio.cpp] Error 1
jom: C:\Users\zhang.2669\Documents\Qt Project\slstudio-master\build-SLStudio-Desktop_Qt_5_4_2_MSVC2012_OpenGL_32bit-Debug\Makefile [debug] Error 2
16:24:35: The process "C:\Qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project SLStudio (kit: Desktop Qt 5.4.2 MSVC2012 OpenGL 32bit)
When executing step "Make"
16:24:35: Elapsed time: 02:39.]

Do you know how to resolve this problem? Thank you!

**Comment by jakobwilm** [comment]
Sorry. No, it is not possible to diagnose this based on the information you provide.
